nyc_taxi_lakehouse:
  target: dev
  outputs:
    dev:
      type: trino
      host: trino
      port: 8080
      user: dbt
      database: iceberg      
      schema: bronze         
      threads: 4
